services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: hirevo-backend
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./app.env:/var/www/.env
        depends_on:
            - mysql

    nginx:
        image: nginx:stable
        container_name: nginx
        ports:
            - "80:80"
            - "6001:6001"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        env_file:
            - .env.docker
        image: mysql:8.0
        ports:
            - "7777:3306"
        container_name: mysql
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
