services:
    app:
        image: ghcr.io/zsoltgombocz/hirevo-backend:latest
        container_name: hirevo-backend
        working_dir: /var/www
        volumes:
            - public:/var/www/public
            - ./app.env:/var/www/.env
            - ./version.json:/var/www/public/version.json:ro
        depends_on:
            - mysql

    caddy:
        image: caddy:latest
        restart: unless-stopped
        depends_on:
            - app
        cap_add:
            - NET_ADMIN
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - public:/var/www/public:ro
            - ./Caddyfile:/etc/caddy/Caddyfile:ro
            - caddy_data:/data
            - caddy_config:/config

    mysql:
        env_file:
            - .env.docker
        image: mysql:8.0
        container_name: mysql
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    public:
    mysql_data:
    caddy_data:
    caddy_config:
