name: CI/CD Pipeline

on:
  push:
    branches:
      - "*"
  release:
    types: [published]

jobs:
  code_analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: pint, phpstan

      - name: Install dependencies
        run: composer install

      - name: Run Pint
        run: ./vendor/bin/pint

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse -c phpstan.neon --memory-limit 1G

  publish_image:
    name: Build & Publish Docker Image
    if: github.event_name == 'release'
    needs: code_analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.actor }}/hirevo-backend

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy to Server
    if: github.event_name == 'release'
    needs: publish_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy deploy configs to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yml,docker/caddy/Caddyfile"
          target: "/home/projects/hirevo-backend"

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd hirevo-backend
            echo "${{ github.ref_name }}" > version.json
            docker pull ghcr.io/${{ github.actor }}/hirevo-backend:latest
            docker compose down
            docker compose up -d
            sleep 15
            docker exec hirevo-backend chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache
            docker exec hirevo-backend php artisan migrate --force
